# docker compose up --build

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Your_password123" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: industrial
      RABBITMQ_DEFAULT_PASS: industrial
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  sql-data:
    build:
      context: .
      dockerfile: services/sql-data/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5102:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=IndustrialPress;User Id=sa;Password=Your_password123;TrustServerCertificate=True"
      ASPNETCORE_URLS: "http://+:8080"

  rest-api:
    build:
      context: .
      dockerfile: services/rest-api/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      sql-data:
        condition: service_started
    ports:
      - "5101:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Redis: "redis:6379"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__User: "industrial"
      RabbitMQ__Password: "industrial"
      Grpc__SqlData: "http://sql-data:8080"

  iot-telemetry:
    build:
      context: .
      dockerfile: services/iot-telemetry/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ConnectionStrings__Redis: "redis:6379"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__User: "industrial"
      RabbitMQ__Password: "industrial"

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - rest-api
